fix: revert order_by fix
breaks the query with
```
 ProgrammingError: (psycopg2.errors.UndefinedTable) missing
         FROM-clause entry for table "task"
         LINE 3: WHERE submission_1.id IN (5, 4, 3, 2, 1) ORDER BY
         task.order...
```
so change reverted - but task attempts in submissions
possibly not in correct order